### ISSUE TITLE
Title ID and name should be unique if you're going to release builds

### ISSUE THREAD

**Issue by ksanislo** [ShinyMK/JKSMK#1]
I'm trying to maintain a list of builds for what is available at the [3DS Homebrew Title Database](https://www.titledb.com), but people are unable to differentiate between two items with identical name/titleid information, so I have no choice but to delist your fork.

If you'd like to be listed, please resubmit a new release with updated information.

Thanks!

-Ken

**Comment by ShinyMK** [comment]
Yup, Next release should have it fixed :)
